version: '2.1'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
        - "5402:5432"
    environment:
      POSTGRES_DB: basiskaart
      POSTGRES_USER: basiskaart
      POSTGRES_PASSWORD: insecure

  importer:
    build: data_import
    links:
      - database
    environment:
      SECRET_KEY: hoi
      DB_NAME: basiskaart
      DB_USER: basiskaart
      DB_PASSWORD: insecure
      BAG_OBJECTSTORE_PASSWORD: insecure
      BGT_OBJECTSTORE_PASSWORD: insecure
    command: >
      bash -c "/app/basiskaart/docker-wait.sh \
              && python /app/basiskaart/import_basiskaart.py"
