version: '3.0'
services:
  database:
    image: amsterdam/postgres11
    ports:
        - "5402:5432"
    environment:
      POSTGRES_DB: basiskaart
      POSTGRES_USER: basiskaart
      POSTGRES_PASSWORD: insecure

  importer:
    build: src/
    links:
      - database
    environment:
      SECRET_KEY: hoi
      DATABASE_NAME: basiskaart
      DATABASE_USER: basiskaart
      DATABASE_PASSWORD: insecure
      GOB_OBJECTSTORE_PASSWORD: ${GOB_OBJECTSTORE_PASSWORD}
      BGT_OBJECTSTORE_PASSWORD: ${BGT_OBJECTSTORE_PASSWORD}
    command: >
      bash -c "./docker-import-db.sh"