version: '2.1'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
        - "5402:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: basiskaart

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/basiskaart:${ENVIRONMENT}
    links:
      - database
    environment:
      BAG_OBJECTSTORE_PASSWORD: ${BAG_OBJECTSTORE_PASSWORD:-insecure}
      BGT_OBJECTSTORE_PASSWORD: $(BGT_OBJECTSTORE_PASSWORD:-insecure}
      DB_NAME: basiskaart
      DB_USER: basiskaart
      DB_HOST: localhost
      DB_PORT: 5432
      DB_PASSWORD: insecure
    command: >
      bash -c "/app/basiskaart/docker-wait.sh \
              && python /app/basiskaart/import_basiskaart.py"

  db-backup:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    links:
      - database
    volumes:
      - ./backups:/tmp/backups
    command: >
      bash -c "echo database:5432:basiskaart:basiskaart:insecure > ~/.pgpass \
              && chmod 600 ~/.pgpass \
              && pg_dump --clean \
                          -Fc \
                          -n kbk10 \
                          -n kbk50 \
                          -n bgt \
                          -U basiskaart \
                          -h database -p 5432 \
                          basiskaart > /tmp/backups/database.dump"
