version: '2.1'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5402:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: basiskaart

  tests:
    build: .
    links:
      - database
    environment:
      DATABASE_NAME: basiskaart
      DATABASE_PASSWORD: insecure
    command: bash -c "/app/basiskaart/tests.sh"

  importer:
    build: .
    links:
      - database
    environment:
      BASISKAART_OBJECTSTORE_PASSWORD: $${BASISKAART_OBJECTSTORE_PASSWORD:-insecure}
      BGT_OBJECTSTORE_PASSWORD: $$(BGT_OBJECTSTORE_PASSWORD:-insecure}
      DB_NAME: basiskaart
      DB_USER: basiskaart
      DB_HOST: localhost
      DB_PORT: 5432
      DB_PASSWORD: insecure
    command: >
      bash -c "/app/docker-wait.sh \
              && python /app/import_basiskaart.py"

  importer_kbk10:
    build: .
    links:
      - database
    environment:
      BASISKAART_OBJECTSTORE_PASSWORD: $${BASISKAART_OBJECTSTORE_PASSWORD:-insecure}
      BGT_OBJECTSTORE_PASSWORD: $$(BGT_OBJECTSTORE_PASSWORD:-insecure}
      DB_NAME: basiskaart
      DB_USER: basiskaart
      DB_HOST: localhost
      DB_PORT: 5432
      DB_PASSWORD: insecure
    command: >
      bash -c "/app/docker-wait.sh \
              && python /app/import_basiskaart.py --basiskaart=kbk10"

  importer_kbk50:
    build: .
    links:
      - database
    environment:
      BASISKAART_OBJECTSTORE_PASSWORD: $${BASISKAART_OBJECTSTORE_PASSWORD:-insecure}
      BGT_OBJECTSTORE_PASSWORD: $$(BGT_OBJECTSTORE_PASSWORD:-insecure}
      DB_NAME: basiskaart
      DB_USER: basiskaart
      DB_HOST: localhost
      DB_PORT: 5432
      DB_PASSWORD: insecure
    command: >
      bash -c "/app/docker-wait.sh \
              && python /app/import_basiskaart.py --basiskaart=kbk50"

  importer_bgt:
    build: .
    links:
      - database
    environment:
      BASISKAART_OBJECTSTORE_PASSWORD: $${BASISKAART_OBJECTSTORE_PASSWORD:-insecure}
      BGT_OBJECTSTORE_PASSWORD: $$(BGT_OBJECTSTORE_PASSWORD:-insecure}
      DB_NAME: basiskaart
      DB_USER: basiskaart
      DB_HOST: localhost
      DB_PORT: 5432
      DB_PASSWORD: insecure
    command: >
      bash -c "/app/docker-wait.sh \
              && python /app/import_basiskaart.py --basiskaart=bgt"

  db-backup:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    links:
      - database
    volumes:
      - ./backups:/tmp/backups
    command: >
      bash -c "echo database:5432:basiskaart:basiskaart:insecure > ~/.pgpass \
              && chmod 600 ~/.pgpass \
              && pg_dump --clean \
                          -Fc \
                          -n kbk10 \
                          -n kbk50 \
                          -n bgt \
                          -n teksten \
                          -U basiskaart \
                          -h database -p 5432 \
                          basiskaart > /tmp/backups/database.dump"
