database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_USER: basiskaart

importer:
  build: .
  links:
    - database:database
  volumes:
    - /mnt/data/diva_import:/app/kbk
  environment:
    DB_NAME: basiskaart
    DB_USER: basiskaart
    DB_PASSWORD: insecure
  command: >
    bash -c "/app/docker-wait.sh \
            && /app/createdb.sh \
            && /app/import_kbk10.sh \
            && /app/import_kbk50.sh \
            && /app/create_indexes.sh"

db-backup:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  links:
    - database:db
  volumes:
    - ./backups:/tmp/backups
  command: >
    bash -c "echo db:5432:basiskaart:basiskaart:insecure > ~/.pgpass \
            && chmod 600 ~/.pgpass \
            && pg_dump --clean \
                        -Fc \
                        -n kbk10 \
                        -n kbk50 \
                        -U basiskaart \
                        -h db -p 5432 \
                        basiskaart > /tmp/backups/database.dump"
