version: '3.0'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
        - "5402:5432"
    environment:
      POSTGRES_DB: basiskaart
      POSTGRES_USER: basiskaart
      POSTGRES_PASSWORD: insecure

  importer:
    build: src
    links:
      - database
    environment:
      SECRET_KEY: hoi
      DATABASE_NAME: basiskaart
      DATABASE_USER: basiskaart
      DATABASE_PASSWORD: insecure
      BAG_OBJECTSTORE_PASSWORD: ${BAG_OBJECTSTORE_PASSWORD}
      BGT_OBJECTSTORE_PASSWORD: ${BGT_OBJECTSTORE_PASSWORD}
    command: >
      bash -c "/app/.jenkins/docker-wait.sh \
              && python3 ./import_basiskaart.py"
