version: '3.0'
services:
  database:
    image: amsterdam/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: basiskaart
      POSTGRES_DB: basiskaart

  tests:
    build: ..
    links:
      - database
    environment:
      DEBUG: 1
      BAG_OBJECTSTORE_PASSWORD:
      BGT_OBJECTSTORE_PASSWORD:
      DATABASE_NAME: basiskaart
      DATABASE_PASSWORD: insecure
    command: >
      bash -c "/app/docker-wait.sh \
              && flake8 --config=/app/flake.cfg /app/basiskaart \
              && pytest"
