version: '3.0'
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: basiskaart
    volumes:
      - ./backups:/tmp/backups

  importer:
    image: ${DOCKER_REGISTRY_HOST}/datapunt/basiskaart:${ENVIRONMENT}
    links:
      - database
    environment:
      DATABASE_NAME: basiskaart
      DATABASE_USER: basiskaart
      DATABASE_PASSWORD: insecure
      GOB_OBJECTSTORE_PASSWORD:
      BGT_OBJECTSTORE_PASSWORD:
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432
      GOB_OBJECTSTORE_ENV: ${GOB_OBJECTSTORE_ENV}
    command: >
      bash -c "/.jenkins-import/docker-import-db.sh"
