version: '2.1'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: basiskaart

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/basiskaart:${ENVIRONMENT}
    links:
      - database
    environment:
      DB_NAME: basiskaart
      DB_USER: basiskaart
      DB_PASSWORD: insecure
      BAG_OBJECTSTORE_PASSWORD:
      BGT_OBJECTSTORE_PASSWORD:
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432
    command: >
      bash -c "/app/.jenkins/docker-wait.sh \
              && python3 /app/import_basiskaart.py"

  db-backup:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    links:
      - database
    volumes:
      - ./backups:/tmp/backups
    command: >
      bash -c "echo database:5432:basiskaart:basiskaart:insecure > ~/.pgpass \
              && chmod 600 ~/.pgpass \
              && pg_dump --clean \
                          -Fc \
                          -n kbk10 \
                          -n kbk50 \
                          -n bgt \
                          -U basiskaart \
                          -h database -p 5432 \
                          basiskaart > /tmp/backups/database.dump"
